### ISSUE TITLE
Question about UNICORE "Resources"

### ISSUE THREAD

**Issue by espenhgn** [HumanBrainProject/pyunicore#10]
Hi! Hope I found the right channel of inquiry. 

I'm using pyunicore to create jobs on JSC/JUSUF via an HBP/EBRAINS collab, and have a question about the Resources settings explained here: https://sourceforge.net/p/unicore/wiki/Job_Description/
Software like NEST (nest-simulator.org) supports efficient multithreading in conjunction with MPI. Hence I would request some # CPUs as well as # CPUsPerNode alternatively # Nodes, however Unicore appears to force two MPI tasks per physical core (128 on JUSUF), which makes multithreading pointless. One example would be:
```
simulation_job['Resources'] = {
    "Queue": "batch",
    "CPUs": "256",
    "CPUsPerNode": "64",
    "Runtime": "600",
}
```
where I would expect 256 tasks distributed evenly across 4 nodes, but the resulting slurm job script only requests 256 tasks without a set number of nodes. Is there a way to work around this? Requesting a certain # Nodes doesn't help either.

**Comment by espenhgn** [comment]
For the sake of argument, things appear to be parsed correctly in the `UNICORE_Job_1604956632693` files but not in the corresponding `bss_submit_1604956632693` file:
```
$ cat UNICORE_Job_1604956632693 
#!/bin/bash -l 
. /etc/profile > /dev/null 2>&1 
ACTIVE_PROJECT=$(id -gn); export ACTIVE_PROJECT 
jutil env activate -p $ACTIVE_PROJECT > /dev/null 2>&1 
#TSI_SUBMIT
 

#TSI_OUTCOME_DIR /p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80/
#TSI_USPACE_DIR /p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80/
#TSI_STDOUT stdout
#TSI_STDERR stderr
#TSI_JOBNAME UNICORE_Job
#TSI_EMAIL NONE
#TSI_TIME 600
#TSI_NODES NONE
#TSI_TOTAL_PROCESSORS 256
#TSI_PROCESSORS 256
#TSI_QUEUE batch
UC_PROCESSORS=256; export UC_PROCESSORS;
UC_TOTAL_PROCESSORS=256; export UC_TOTAL_PROCESSORS;
UC_RUNTIME=600; export UC_RUNTIME;
UC_MEMORY_PER_NODE=-1; export UC_MEMORY_PER_NODE;
#TSI_SSR_CPUSPERNODE 64
#TSI_SSR_NODES 4
 
#TSI_SCRIPT
#TSI_UMASK 77
umask 77
UC_EXECUTABLE='

<misc job instructions>

'; export UC_EXECUTABLE
UC_USERDN="UID=espen.hagen@nmbu.no"; export UC_USERDN
PATH=$PATH:. ; export PATH
cd /p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80/
chmod u+x module 2> /dev/null 
rm -f /p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80//UNICORE_SCRIPT_EXIT_CODE

<misc job instructions>

echo $? > /p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80//UNICORE_SCRIPT_EXIT_CODE

#TSI_IDENTITY hagen2 icei-hbp-2020-0004:DEFAULT_GID
```
```
$ cat bss_submit_1604956632693
#!/bin/bash
#SBATCH --job-name=UNICORE_job
#SBATCH --partition=batch
#SBATCH --account=icei-hbp-2020-0004
#SBATCH --ntasks=256
#SBATCH --time=10
#SBATCH --output=/p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80//stdout
#SBATCH --error=/p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80//stderr
#SBATCH --chdir=/p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80/
umask 77
/p/scratch/icei-hbp-2020-0004/unicore-jobs//203386db-a6e3-45db-948f-dfb2133ffe80//UNICORE_Job_1604956632693
[hagen2@jsfl01 203386db-a6e3-45db-948f-dfb2133ffe80]$ cat UNICORE_Job_1604956632693 
#!/bin/bash -l 
. /etc/profile > /dev/null 2>&1 
ACTIVE_PROJECT=$(id -gn); export ACTIVE_PROJECT 
jutil env activate -p $ACTIVE_PROJECT > /dev/null 2>&1 
#TSI_SUBMIT
```

**Comment by BerndSchuller** [comment]
hi,

the "CPUs" value takes precedence before the Nodes+CPUsPerNode combination

If I understand correctly, to get 256 tasks spread across 4 nodes, wouldn't

```
simulation_job['Resources'] = {
    "Queue": "batch",
    "Nodes": "4",
    "CPUsPerNode": "64",
    "Runtime": "600",
}
```

do the right thing? This will result in a slurm allocation

```
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=64
``` 

If needed, you can assign the --cpus-per-task in the "srun" invocation if I am not mistaken. Would that work for you?

Best regards,
Bernd

**Comment by espenhgn** [comment]
Setting
```
    "Nodes": "4",
    "CPUsPerNode": "128",
```
resulted in a job script with
```
#SBATCH --ntasks=1
```
and again no # nodes, which is quite wrong ;)
The same occurs if I request a number of nodes only, so using the --cpus-per-task parameter with srun would also not work.

**Comment by BerndSchuller** [comment]
that's not how it should be, I'll take a look...

**Comment by espenhgn** [comment]
Thanks! Btw., I should use the latest pyunicore version by including `!pip install pyunicore --upgrade` in my notebook.

Best regards,
Espen

**Comment by BerndSchuller** [comment]
all good, the pyunicore is not the issue, it was a misconfiguration on the jusuf installation.
I've fixed that. If you now set Nodes+CPUsPerNode you'll get the documented behaviour. As the JSC systems are configured now, you should always use Nodes+CPUsPerNode

**Comment by espenhgn** [comment]
Great, seems to work now. Thanks for the quick help!
