### ISSUE TITLE
Transfer ownership of PyPI project

### ISSUE THREAD

**Issue by BerndSchuller** [HumanBrainProject/pyunicore#14]
Travis-CI.org is going away, and the current way of package deployment to 
https://pypi.org/project/pyunicore/ does no longer seem to work.
I'd like to use GitHub actions for deployment, but this requires being able to upload to PyPi.

Current owner is https://pypi.org/user/pyunicore/ which should be Mike G.  - if he is no longer available we need to go through the official process for transferring ownership

**Comment by mgeplf** [comment]
Long time no talk; I'm still around - I have the password, what is the best way to get it to you?

**Comment by BerndSchuller** [comment]
thanks, that's good to hear...
email "b.schuller at fz-juelich.de" is probably simplest, I'll change it immediately
