### ISSUE TITLE
Bug Path.remove

### ISSUE THREAD

**Issue by mtar** [HumanBrainProject/pyunicore#15]
https://github.com/HumanBrainProject/pyunicore/blob/2713b595a886e65edd603dee0d53b8f6270e0633/pyunicore/client.py#L666-L668

Hi, I get an error when I call the method `remove` on a `Path` object
`NameError: name 'name' is not defined`

**Comment by BerndSchuller** [comment]
thank you! I just pushed a fix for this. The fix is in version 0.9.6 available from pypi, just update via "pip install -U pyunicore"
