### ISSUE TITLE
Specify required minimal Python version

### ISSUE THREAD

**Issue by schmitts** [HumanBrainProject/pyunicore#19]
What is the minimal Python version required? Can you please specify it at an appropriate place?

**Comment by BerndSchuller** [comment]
I checked with "vermin" (https://github.com/netromdk/vermin), and it says 2.7 or 3.0, which is pretty much "any python"
Since 2.x is no longer supported, I'd say "3.0"
Does it even make sense to specify this in setup.py or wherever?

**Comment by schmitts** [comment]
#20 needs at least 3.7 and I was not sure when proposing the change. It would be correct to use https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires.
