### ISSUE TITLE
Raise more specific Exceptions

### ISSUE THREAD

**Issue by zyzzyxdonta** [HumanBrainProject/pyunicore#27]
Hi!

It would be nice if the Client would raise more specific exceptions. E.g. if authentication with the server failed, a `UnicoreAuthenticationError` (or whatever) would be better than the generic `Exception` [here](https://github.com/HumanBrainProject/pyunicore/blob/58ae2e5aeccab070624c3afac4c712513fca1e58/pyunicore/client.py#L296)

Everything works as intended but some code checkers/analysers will complain about this. E.g. PyCharm says "Too broad exception clause" 😄

**Comment by BerndSchuller** [comment]
good point - thanks!
