### ISSUE TITLE
Can't retrieve output files of a job on windows

### ISSUE THREAD

**Issue by davidbacter01** [HumanBrainProject/pyunicore#29]
Hi!
While trying to access the output of a job there is an error:
404 Server Error: Not Found for url: https://zam2125.zam.kfa-juelich.de:9112/JUSUF/rest/core/storages/1c7ee596-c470-480b-ac4d-0d8185ea36d8-uspace/files%5C
I am using windows for development and I believe this error is due to the fact that normpath is being used on the url and as seen in the error, the URL ends with the unicode code for '\' which is what normpath does to '/'.
Here is how I am trying to access the files:
token = 'my_real_token'
import pyunicore.client as unicore_client

transport = unicore_client.Transport(token, oidc=True)
registry = unicore_client.Registry(transport, unicore_client._HBP_REGISTRY_URL)

sites = registry.site_urls
site_url = sites['JUSUF']
client = unicore_client.Client(transport, site_url)
jobs = client.get_jobs()

jobs[0].working_dir.listdir()

**Comment by BerndSchuller** [comment]
thank you!

**Comment by davidbacter01** [comment]
Can you please approximate a time frame for the release with the fix if possible? Also in past versions there used to be a function  for getting a dict with the available sites called get_sites. Is it possible to get the function back or provide an example of what would be the best way of getting it (I have a feeling that the way I did it in the example above is not ideal)?

**Comment by BerndSchuller** [comment]
Sure! The release is available - 0.11.1
The get_sites() has been removed, since using a Registry client (as you did) does the same thing.
Once you have the Registry , you can get a site client more easily:
```
client = registry.site("JUSUF")
```

**Comment by davidbacter01** [comment]
Thank you for your prompt response!
