### ISSUE TITLE
Unsupported type annotations in various places in the code

### ISSUE THREAD

**Issue by zyzzyxdonta** [HumanBrainProject/pyunicore#41]
Hi!

I just noticed that the code uses the pipe symbol as a shorthand for union types in various places, e.g. here:

https://github.com/HumanBrainProject/pyunicore/blob/1.1.0/pyunicore/client.py#L215

However, this has only been allowed since Python 3.10. With earlier Python versions, this results in an error, e.g.:

```
  File "/builds/heliport/heliport/.cache/poetry/virtualenvs/heliport-c9km1fGm-py3.9/lib/python3.9/site-packages/pyunicore/client.py", line 215, in Resource
    self, security: Credential | Transport, resource_url: str, cache_time=_DEFAULT_CACHE_TIME
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

pyunicore can be installed using Python >= 3.7:

https://github.com/HumanBrainProject/pyunicore/blob/1.1.0/setup.py#L13

**Comment by BerndSchuller** [comment]
Thanks a lot, David! Fixed in version 1.1.1
