### ISSUE TITLE
Sorting by SubmissionTime

### ISSUE THREAD

**Issue by antonelepfl** [HumanBrainProject/pyunicore#8]
When I fetch the results using `jobs = client.get_jobs()` the jobs list are not sorted.
Is there any way to pass some parameter to sort of get by default this job sorted ?

**Comment by BerndSchuller** [comment]
sorry, there is no way to influence the order in the client when retrieving the job list (because the server does not support this)

**Comment by BerndSchuller** [comment]
this is a server thing so closing it here
