### ISSUE TITLE
dict-key-error when running "rename" function of storage object

### ISSUE THREAD

**Issue by BrainModes** [HumanBrainProject/pyunicore#9]
storage.rename(source=tmp_source, target=freesurfer_target)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-44-2edd011a8c32> in <module>
----> 1 storage.rename(source=sourcefile, target=targetfile)

/opt/app-root/lib/python3.6/site-packages/pyunicore/client.py in rename(self, source, target)
    444                 'to': target,
    445                 }
--> 446         return self.transport.post(url=self.path_urls['rename'], json=json)
    447 
    448     def copy(self, source, target):

KeyError: 'rename'

The key "rename" does not exist, only "action:rename"

**Comment by BerndSchuller** [comment]
indeed, sorry for the oversight. Just pushed a fix, should be on pypi shortly (v0.5.9)
